# Generated by Django 2.0.7 on 2019-05-31 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=20)),
                ('purchased_date', models.DateField()),
                ('base_price', models.FloatField(default=0.0)),
                ('plus_fees', models.FloatField(default=0.0)),
                ('net_price', models.FloatField(default=0.0)),
                ('pump_price', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('gallons_pumped', models.FloatField(default=0.0)),
                ('gross_amount', models.FloatField(default=0.0)),
                ('net_amount', models.FloatField(default=0.0)),
                ('discount_on_fuel', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
